version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    cooldown:
      default-days: 7
    groups:
      aws-sdk:
        patterns:
          - "@aws-sdk/*"
      typescript:
        patterns:
          - "typescript"
