name = "telegram-sync"
main = "src/index.ts"
compatibility_date = "2025-10-05"

[build]
command = "pnpm build"

[observability.logs]
enabled = true

# R2 bucket binding
[[r2_buckets]]
binding = "R2_BUCKET"

# KV namespace binding
[[kv_namespaces]]
binding = "KV_STORE"

[placement]
mode = "smart"

# Note: Environment variables are managed via:
# - wrangler secret put R2_BUCKET_NAME (for production)
# - .dev.vars file (for local development)
# - Environment variables in CI/CD
# Never commit actual secrets or sensitive values to this file!
